### ISSUE TITLE
NoClassDefFoundError creating a dashboard

### ISSUE THREAD

**Issue by phillipviana** [vipinsthename/environment-dashboard#131]
I've been using the environment dashboard in Jenkins for a few months now. One day I logged in and my dashboard (I only had one) was totally gone!

I tried recreating it but I hit a NoClassDefFoundError:

```
Jul 12, 2016 10:20:49 PM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Error while serving http://146.89.179.239:7080/createView
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:324)
	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:52)
	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:167)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:100)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:201)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:178)
	at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:85)
	at org.jvnet.hudson.plugins.monitoring.HudsonMonitoringFilter.doFilter(HudsonMonitoringFilter.java:104)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jenkinsci.plugins.environmentdashboard.EnvDashboardView
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.kohsuke.stapler.RequestImpl.invokeConstructor(RequestImpl.java:525)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:777)
	at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:83)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:674)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:478)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:474)
	at hudson.model.Descriptor.newInstance(Descriptor.java:590)
	at hudson.model.View.create(View.java:1273)
	at jenkins.model.Jenkins.doCreateView(Jenkins.java:3574)
	... 73 more
```

I tried removing and reinstalling the plug-in, but no luck... The stack trace above is all that jenkins.log shows.

The contents of my environment dashboard plugin folder can be found below. Any ideas?

```
[root@deehacp014ccpra environment-dashboard]# pwd
/var/lib/jenkins/plugins/environment-dashboard
[root@deehacp014ccpra environment-dashboard]# find .
.
./css
./css/blink.css
./css/bootstrap-theme.min.css
./css/bootstrap.min.css
./WEB-INF
./WEB-INF/lib
./WEB-INF/lib/org
./WEB-INF/lib/org/jenkinsci
./WEB-INF/lib/org/jenkinsci/plugins
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/ListItem$DescriptorImpl.class
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/EnvDashboardView.class
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder/help-packageName.html
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder/help-buildJob.html
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder/help-addColumns.html
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder/DescriptorImpl
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder/DescriptorImpl/doCheckComponentName.stapler
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder/DescriptorImpl/doCheckNumberOfDays.stapler
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder/DescriptorImpl/doCheckNameOfEnv.stapler
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder/DescriptorImpl/doCheckBuildNumber.stapler
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder/help-buildNumber.html
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder/help-numberOfDays.html
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder/help-componentName.html
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder/config.jelly
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder/help-nameOfEnv.html
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder/global.jelly
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/utils
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/utils/DBConnection.class
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder$DescriptorImpl.class
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/ListItem.stapler
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/EnvDashboardView$DescriptorImpl.class
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder$1TearDownImpl.class
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/ListItem.class
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder.class
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/EnvDashboardView.stapler
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/DashboardBuilder.stapler
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/EnvDashboardView
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/EnvDashboardView/help-deployHistory.html
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/EnvDashboardView/main.jelly
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/EnvDashboardView/newViewDetail.jelly
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/EnvDashboardView/index.jelly
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/EnvDashboardView/DescriptorImpl
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/EnvDashboardView/DescriptorImpl/doDropColumn.stapler
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/EnvDashboardView/help-envOrder.html
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/EnvDashboardView/configure-entries.jelly
./WEB-INF/lib/org/jenkinsci/plugins/environmentdashboard/EnvDashboardView/help-compOrder.html
./WEB-INF/lib/classes.jar
./WEB-INF/lib/index.jelly
./WEB-INF/lib/META-INF
./WEB-INF/lib/META-INF/annotations
./WEB-INF/lib/META-INF/annotations/hudson.Extension
./WEB-INF/lib/META-INF/annotations/org.kohsuke.stapler.export.ExportedBean
./WEB-INF/lib/h2-1.4.181.jar
./WEB-INF/licenses.xml
./META-INF
./META-INF/MANIFEST.MF
./META-INF/maven
./META-INF/maven/org.jenkins-ci.plugins
./META-INF/maven/org.jenkins-ci.plugins/environment-dashboard
./META-INF/maven/org.jenkins-ci.plugins/environment-dashboard/pom.xml
./META-INF/maven/org.jenkins-ci.plugins/environment-dashboard/pom.properties
./.timestamp2
```

Thanks
Phil

**Comment by rvcoutinho** [comment]
Same here
