### ISSUE TITLE
Getting exceptions about h2 in log file

### ISSUE THREAD

**Issue by guillaume-ggo** [vipinsthename/environment-dashboard#138]
Hi,

On a Jenkins instance 2.46.1 LTS with the 1.1.7 version of the Environment Dashboard plugin, we're getting lot of exceptions about h2 like that in the log file jenkins_dashboard.trace.db:

2017-07-03 12:36:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-188]
2017-07-03 12:36:02 jdbc[27]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-188]
2017-07-03 12:36:02 jdbc[51]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-188]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at org.jenkinsci.plugins.environmentdashboard.utils.DBConnection.getConnection(DBConnection.java:35)
	at org.jenkinsci.plugins.environmentdashboard.EnvDashboardView.runQuery(EnvDashboardView.java:263)
	at org.jenkinsci.plugins.environmentdashboard.EnvDashboardView.getCompDeployed(EnvDashboardView.java:381)

...
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-188]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 156 more

We have a view to monitor 6 environments and three  components.

Did you have yet such exceptions ?

Thanks in advance and ask me if you want more details.

**Comment by Zeckie** [comment]
We are having problems with the 'jenkins_dashboard.trace.db' file growing by about 2GB per day.
There are some people who have the dashboard open all day (with autorefresh reloading every 10 seconds).

The exceptions in our log look quite similar.

We also get this one - seems to show the cause:
(timestamp)  jdbc[489]: java.lang.Exception: Open Stack Trace
                at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
                at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:119)
                at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
                at org.h2.Driver.connect(Driver.java:72)
                at java.sql.DriverManager.getConnection(DriverManager.java:664)
                at java.sql.DriverManager.getConnection(DriverManager.java:270)
                at org.jenkinsci.plugins.environmentdashboard.utils.DBConnection.getConnection(DBConnection.java:35)
                at org.jenkinsci.plugins.environmentdashboard.EnvDashboardView.runQuery(EnvDashboardView.java:263)
                at org.jenkinsci.plugins.environmentdashboard.EnvDashboardView.getCompLastDeployed(EnvDashboardView.java:475)
                at sun.reflect.GeneratedMethodAccessor296.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
...

It looks to me like the issue is in [EnvDashboardView.java near line 481](https://github.com/vipinsthename/environment-dashboard/blob/master/src/main/java/org/jenkinsci/plugins/environmentdashboard/EnvDashboardView.java#L481)
If an exception is thrown in the try block, then line 480 is not run, and the connection is not closed,
