### ISSUE TITLE
Publich latest dashboard plugin to Jenkins with declarative pipeline support

### ISSUE THREAD

**Issue by RobertNorthard** [vipinsthename/environment-dashboard#150]
The latest version of this plugin has not been published and therefore not able to use the dashboard with declarative pipelines.

**Comment by willwh** [comment]
@RobertNorthard it's not quite ready to go in its current state.

We are working on migrating the plugin to the jenkinsci group on github, please feel free to follow this issue: https://issues.jenkins-ci.org/browse/HOSTING-808

I'm currently travelling, so I have very limited time, until the start of august.

If you want to install a working version of the plugin, with pipeline support, you can do the following:

```
git clone https://github.com/willwh/environment-dashboard.git
git checkout HOSTING-808
mvn install
```

**Comment by willwh** [comment]
With recent version bump of https://github.com/findbugsproject/findbugs, this plugin is no longer building happily.... and there is quite a bit of work to do to sort things out.... I'm working on things as I can in the branch above, although, I am travelling again the next couple of days.

Expect some issue cleanup as I sit waiting in airports ;)

**Comment by gitkent** [comment]
Hi guys, just wondering if there is any updates regarding this feature? It will be very useful for us. Thanks

**Comment by willwh** [comment]
Not yet, still working on things, there is a lot to fix.

**Comment by e-moshaya** [comment]
any update on this?

**Comment by willwh** [comment]
@e-moshaya we are just waiting on the repository being migrated to the `jenkinsci` team, which is in process now. Once that is complete, we'll be cutting a new release with pipeline support. That code is all in master now, so if you wanted to build and use the plugin, do the following:

 - Check out the `master` branch
 - run the following to build the plugin:
```
mvn install -Dmaven.javadoc.skip=true -Dspotbugs.failOnError=false
```

This will compile things to `/your/checkout/target` - grab the `environment-dashboard.hpi` and you can install that from the "Advanced" tab of the plugin management page in Jenkins.

Hopefully it's officially out soon :)

**Comment by EnricoSemrau** [comment]
Hey guys, I still cant compile - anyone able to help? I am completely new to this maven thingy.
When trying to run command: mvn install -Dmaven.javadoc.skip=true -Dspotbugs.failOnError=false

Build fails with:
[ERROR] java.nio.file.NoSuchFileException: /Users/*me*/Downloads/environment-dashboard/target/classes/META-INF/annotations/org.kohsuke.stapler.export.ExportedBean
[ERROR] java.nio.file.NoSuchFileException: /Users/*me*/Downloads/environment-dashboard/target/classes/META-INF/annotations/org.jenkinsci.Symbol
[ERROR] java.nio.file.NoSuchFileException: /Users/*me*/Downloads/environment-dashboard/target/classes/META-INF/annotations/hudson.Extension

**Comment by gitkent** [comment]
@EnricoSemrau What maven version you using? My build completed successfully with the following version:

```
 └─ $ ▶ mvn --version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-05T06:00:29+11:00)
Maven home: /Users/<me>/.asdf/installs/maven/3.6.1
Java version: 1.8.0_211, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"
```

**Comment by EnricoSemrau** [comment]
@gitkent thanks for your response.

mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 13.0.2, vendor: N/A, runtime: /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home
Default locale: en_DE, platform encoding: US-ASCII
OS name: "mac os x", version: "10.15.2", arch: "x86_64", family: "mac"

I notice the difference is in java version - you think that might be the issue? maybe your version satisfies some of the missing dependencies.

**Comment by gitkent** [comment]
@EnricoSemrau yup, that might be the reason. (Don't think it is compatible with java 13 yet?)

**Comment by willwh** [comment]
> @EnricoSemrau yup, that might be the reason. (Don't think it is compatible with java 13 yet?)

That's correct, as per: https://jenkins.io/doc/administration/requirements/java/ JRE 8 and JRE 11 are supported currently.

**Comment by akhilkumar2601** [comment]
Hey Guys,

can you help me with this?
Error:
java.lang.NoSuchMethodError: No such DSL method 'environmentDashboard' found among steps [ansiColor, archive, bat, build, catchError, checkout, deleteDir, dir, dockerFingerprintFrom, dockerFingerprintRun, echo, emailext, emailextrecipients, envVarsForTool, error, fileExists, findBuildScans, getContext, git, input, isUnix, jiraComment, jiraIssueSelector, jiraSearch, junit, library, libraryResource, load, lock, mail, milestone, node, parallel, powershell, properties, publishHTML, pwd, pwsh, readFile, readTrusted, resolveScm, retry, script, sh, slackSend, slackUploadFile, sleep, sshagent, stage, stash, step, svn, timeout, timestamps, tm, tool, unarchive, unstable, unstash, validateDeclarativePipeline, waitUntil, warnError, withContext, withCredentials, withDockerContainer, withDockerRegistry, withDockerServer, withEnv, wrap, writeFile, ws] or symbols [all, allOf, always, ant, antFromApache, antOutcome, antTarget, any, anyOf, apiToken, architecture, archiveArtifacts, artifactManager, authorizationMatrix, batchFile, bitbucket, bitbucketBranchDiscovery, bitbucketForkDiscovery, bitbucketPublicRepoPullRequestFilter, bitbucketPullRequestDiscovery, bitbucketSshCheckout, bitbucketTagDiscovery, bitbucketTrustEveryone, bitbucketTrustNobody, bitbucketTrustProject, bitbucketTrustTeam, bitbucketWebhookConfiguration, bitbucketWebhookRegistration, booleanParam, branch, brokenBuildSuspects, brokenTestsSuspects, buildButton, buildDiscarder, buildDiscarders, buildingTag, caseInsensitive, caseSensitive, certificate, changeRequest, changelog, changeset, checkoutToSubdirectory, choice, choiceParam, cleanWs, clock, command, credentials, cron, crumb, cssText, cssUrl, culprits, defaultFolderConfiguration, defaultView, demand, developers, disableConcurrentBuilds, disableResume, docker, dockerCert, dockerfile, downstream, dumb, durabilityHint, envVars, environment, equals, expression, faviconUrl, file, fileParam, filePath, fingerprint, frameOptions, freeStyle, freeStyleJob, fromScm, fromSource, git, gitBranchDiscovery, gitHubBranchDiscovery, gitHubBranchHeadAuthority, gitHubExcludeArchivedRepositories, gitHubForkDiscovery, gitHubPullRequestDiscovery, gitHubSshCheckout, gitHubTagDiscovery, gitHubTrustContributors, gitHubTrustEveryone, gitHubTrustNobody, gitHubTrustPermissions, gitParameter, gitTagDiscovery, github, githubPush, googlechatnotification, gradle, headRegexFilter, headWildcardFilter, hyperlink, hyperlinkToModels, inheriting, inheritingGlobal, installSource, isRestartedRun, jdk, jdkInstaller, jgit, jgitapache, jnlp, jobBuildDiscarder, jobName, jsUrl, label, lastDuration, lastFailure, lastGrantedAuthorities, lastStable, lastSuccess, legacy, legacySCM, list, local, location, logRotator, loggedInUsersCanDoAnything, masterBuild, maven, maven3Mojos, mavenErrors, mavenMojos, mavenWarnings, modernSCM, myView, newContainerPerStage, node, nodeProperties, nonInheriting, none, not, overrideIndexTriggers, paneStatus, parallelsAlwaysFailFast, parameters, password, pattern, permanent, pipeline-model, pipeline-model-docker, pipelineTriggers, plainText, plugin, pollSCM, preserveStashes, projectNamingStrategy, proxy, queueItemAuthenticator, quietPeriod, rateLimitBuilds, recipients, requestor, resourceRoot, run, runParam, sSHLauncher, schedule, scmRetryCount, scriptApproval, scriptApprovalLink, search, security, shell, simple-theme-plugin, simpleBuildDiscarder, skipDefaultCheckout, skipStagesAfterUnstable, slackNotifier, slave, sourceRegexFilter, sourceWildcardFilter, ssh, sshUserPrivateKey, stackTrace, standard, status, string, stringParam, swapSpace, tag, teamSlugFilter, text, textParam, timezone, tmpSpace, toolLocation, triggeredBy, unsecured, upstream, upstreamDevelopers, userSeed, usernameColonPassword, usernamePassword, viewsTabBar, weather, withAnt, zfs, zip] or globals [currentBuild, docker, env, params, pipeline, scm]
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:202)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor1781.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:160)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:158)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:162)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:132)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:132)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.run(WorkflowScript:41)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:46)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:405)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:317)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:281)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

**Comment by gitkent** [comment]
@akhilkumar2601 , it looks like Jenkins is not picking up your environment-dashboard plugin. Is the plugin installed correctly without dependencies issue?

**Comment by Akin2Silver** [comment]
> @e-moshaya we are just waiting on the repository being migrated to the `jenkinsci` team, which is in the process now. Once that is complete, we'll be cutting a new release with pipeline support. That code is all in master now, so if you wanted to build and use the plugin, do the following:
> 
``
> 
> This will compile things to `/your/checkout/target` - grab the `environment-dashboard.hpi` and you can install that from the "Advanced" tab of the plugin management page in Jenkins.
> 

1. So is this no longer the right place to raise issues? 
2. If I compline and manually install will that cause issues with updating via the plugin center in the future?

**Comment by willwh** [comment]
It has been migrated, I should be publishing a release tomorrow night. Apologies for the wait! 😓

**Comment by Akin2Silver** [comment]
> It has been migrated, I should be publishing a release tomorrow night. Apologies for the wait! 😓

not at all, thanks for getting it sorted :) Hopfully you have better lick getting an update published.
Another one I use has 3 releases out but can't get them into the update center.
